### ISSUE TITLE
Generic Software sound system 

### ISSUE THREAD

**Issue by ForserX** [xrOxygen/xray-oxygen#117]
- OpenAL Soft Problem!

- [ ] Fix for wrap_oal error 
0x0000000007A9C0DF (wrap_oal.dll)

**Comment by revolucas** [comment]
We've had sound related issues as well. Using older wrap_oal.dll (2008) seemed to fix ours. Though, you require x64 binary, that might be more difficult to find.

**Comment by ForserX** [comment]
EAX we do not have, the problem is on all sound cards. Appeared after the update OpenAL Soft. Waiting for his next update.
