### ISSUE TITLE
The Application was Unable to Start Correctly (0xc000007b)

### ISSUE THREAD

**Issue by maxgvz** [xrOxygen/xray-oxygen#121]
Cannot start xRay Oxygen.
Got error "The Application was Unable to Start Correctly (0xc000007b)"
Tried 1.7f.119 and 1.7f.164.
All packages was installed .NET framework 4.7.2 (x64), .NET core runtime 2.0.7 (x64)...
All installed in windows. Java, net, c++, live... everything.
Even replace DirectX files.
Windows 10 licensed (x64).

Other games works fine. Never had that issues before ran this.

**Comment by Xottab-DUTY** [comment]
Maybe you're lack of Visual C++ Redistributable 2017? It's the most common reason why 0xc000007b appeares.

**Comment by maxgvz** [comment]
**Microsoft Visual C++ 2017 Redistributable (x64) - 14.10.25017** - also installed.

**Comment by maxgvz** [comment]
Before this I got error message like "The code execution cannot proceed because OpenAL32.dll was not found". I had copied this file from /bin/ to /bins/ and after this have issue "The Application was Unable to Start Correctly (0xc000007b)".

**Comment by Xottab-DUTY** [comment]
There's installed for OpenAL in `external` folder, please use it instead of just copying.

**Comment by maxgvz** [comment]
It works now! Thank you!
