### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Swartz27** [xrOxygen/xray-oxygen#137]
Create a dev branch. Do all WIP stuff there. Once it's tested and working THEN put it in the main branch.

I understand this is the reason for the appveyor sln file, but when I tried it it also built faulty code.

I have been working hard on a new renderer for you guys (I haven't uploaded it yet because it's WIP and incompatible with some of the changes you guys have made) but this stuff keeps setting me back to the point where I'm considering walking away from X-ray and never looking back. 

I'm not pointing fingers specifically at anyone, and I'm not trying to be a jerk, but I really want to help you guys, but not if it's going to lead to a lot of wasted time and frustration.

However, that small rant aside I do feel you guys overall are doing a fantastic job. X-ray has never been as good as it is now thanks to all of you :)  So although it may sound like I'm chewing you guys out, that's not my goal, I'm just trying trying to help (I'll admit that I was a little pissed when I typed the above, so I may need to look at it later to make sure I wasn't simply being a dick to you guys, and if that is what I did, then I sincerely apologize, as I do like you guys).

**Comment by Swartz27** [comment]
Alright, just re-read this. Sorry about this guys, I was in a really bad mood earlier, had nothing to do with you. As I'm sure you're all aware I have some anger issues, which I'm trying my best to resolve. Luckily weed does the trick and mellows me the fuck out. Sorry about this. Closing it now.

**Comment by ForserX** [comment]
If you want, I can give access to the main repository. Create a separate branch and send the changes.

**Comment by Swartz27** [comment]
@ForserX I appreciate the offer, but for now what I will do is commit the changes that will work with things currently to my repo, then do a pull request. Then I'll create a new branch with the WIP renderer (just need to clean it a bit first). 
At some point, once I've shown I know what I'm doing, then I would be willing to accept your generous offer.
