### ISSUE TITLE
Unable to run game

### ISSUE THREAD

**Issue by derBABO88** [xrOxygen/xray-oxygen#149]
Hello,

I compiled the solution without any errors. However, when I replace the original game dll's with the newly compiled ones from Oxygen 1.7, xrEngine.exe throws an application error saying the app cannot be correctly started (0xc000007b).

Any clue as to what went wrong?

**Comment by ForserX** [comment]
Install OpenAL Soft. 
game/external/
And use xrPlay.exe. (Double click)

**Comment by ForserX** [comment]
Don't replace original bin. Creat new directory. Sample: bins

**Comment by AgronomNN** [comment]
1.7f.218 release working, 1.7f.352 throws apperror, with no logs at all

**Comment by AgronomNN** [comment]
[[02.06.2018 21.49.28].log](https://github.com/xrOxygen/xray-oxygen/files/2065275/02.06.2018.21.49.28.log)

**Comment by ForserX** [comment]
Delete user.ltx

**Comment by AgronomNN** [comment]
Yes, this help, thanks
