### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by derBABO88** [xrOxygen/xray-oxygen#150]
I'm getting an application error when trying to run the game saying "incompatible hardware".
[[04.06.2018 21.56.40].log](https://github.com/xrOxygen/xray-oxygen/files/2069815/04.06.2018.21.56.40.log)

**Comment by ForserX** [comment]
1. Delete user.ltx
2. Your PC support full dx9?

**Comment by derBABO88** [comment]
I tried deleting user.ltx from the Documents folder, it didn't help. Yes PC does support dx9.
[[04.06.2018 22.19.02].log](https://github.com/xrOxygen/xray-oxygen/files/2069846/04.06.2018.22.19.02.log)

**Comment by ForserX** [comment]
```
c:/users/hepp-pc/source/repos/xray-oxygen-master/binaries/x64/release\gamedata\configs\system.ltx
```
WTF?! 
Use COP directoris

**Comment by derBABO88** [comment]
Can you tell me how the project has to be set up within Visual Studio? Maybe I'm doing something wrong in setting up the paths or folders. Is there a guide / manual how to set this up correctly?

**Comment by Xottab-DUTY** [comment]
xrPlay -> Properties -> Debugging -> Working directory -> Set this to COP root folder.

**Comment by aregic** [comment]
Same error for me. None of these solutions helped.
[[19.11.2018 20.53.12].log](https://github.com/xrOxygen/xray-oxygen/files/2596868/19.11.2018.20.53.12.log)

**Comment by SevastyanDark** [comment]
@aregic Did you compiled renderers?

**Comment by aregic** [comment]
For now I'm just trying to make it work by using the built release. The renderers are next to the xrPlay.exe

**Comment by SevastyanDark** [comment]
@ForserX
