### ISSUE TITLE
Ryzen cpu bug

### ISSUE THREAD

**Issue by MatthewKush** [xrOxygen/xray-oxygen#152]
When playing with lm-dex's repository, my Ryzen 1700 is correctly identified as having 8 cores, 16 threads.
However in this repository, it says I have 16 cores, and 16 threads.
It's also a bit slower CPU-wise.

This is on Release x64 build.

**Comment by ForserX** [comment]
Oxygen CPUID incorrect checking SMID on Ryzon.

**Comment by ForserX** [comment]
Fixed on https://github.com/xrOxygen/xray-oxygen/commit/399e9e440c6d5bb036ba40dba14942fb02318f76
