### ISSUE TITLE
Outdated invite Discord link

### ISSUE THREAD

**Issue by UAVXP** [xrOxygen/xray-oxygen#210]
Discord link that you have at project description is dead. Please, make another one

**Comment by ForserX** [comment]
https://discord.gg/gp5M7qz

**Comment by UAVXP** [comment]
Strange, it shows that this invite is invalid too. I was never been at this server and cannot be banned. Also, user server limit is not reached

**Comment by UAVXP** [comment]
Okay, that was my fault - I was not logged in at my browser
