### ISSUE TITLE
minor bug - hud constantly flickers while aiming with a weapon

### ISSUE THREAD

**Issue by jimmon89** [xrOxygen/xray-oxygen#214]
I've tried with enhanced lighting DX9 and 11, the entire time i'm aimed down sights the HUD repeatedly flickers on top of my weapon/scope, with or without a scope makes little difference.
![off](https://user-images.githubusercontent.com/6391541/45260064-e30ea480-b3aa-11e8-9594-efa1c52b8d37.png)
![on](https://user-images.githubusercontent.com/6391541/45260065-e30ea480-b3aa-11e8-9197-0fb173681451.png)
basically i keeps going between the two images here
I've tried with the latest Appveyor build for the master branch as well as the latest official release, no difference between the two tested releases.

What should be happening is obviously the state of the HUD should either always be on regardless of being aimed, or hidden when aimed but only if using a scope, not flashing between the two rapidly

--edit--
OK, so i was testing again without a scope, and the HUD does not seem to flicker. i stand corrected on my previous statement. with a scope still flickers though. so it would appear to be some kind of z-fighting involving the scope and HUD overlays
--edit--

--edit 2--
turned on the range display and dynamic cross-hair and the parts over top of the weapon (IE. the range and cross-hair) still flicker, but the rest doesn't. so i was partially correct in my first statement. and additionally if i turn on hide weapon the cross-hair and range display still flicker.
--edit 2--

 - OS: windows 7 64 bit
 - Video Resolution: 1920x1080
 - Motherboard: Gigabyte GA-78LMT-S2 Rev. 2
 - Chip set: AMD - 780G
 - South Bridge: AMD - SB700
 - RAM: 2x 8Gb - DDR3
 - RAM Bandwidth: PC3-10700 - 667MHz
 - CPU: AMD FX 6100 - 3.1GHz - 6 core - supports AVX
 - Used PCI: Express 16x
 - GPU: Zotac nVidia Geforce GTX 1050 Ti OC Edition - Rev. A1
 - GPU Clock: 1392 MHz
 - Mem. Clock: 1752 MHz
 - Boost Clock: 1506 MHz
 - Cuda Cores: 768
 - Mem. Transfer rate: 7008 MHz
 - Mem. Interface: 128 bit
 - Memory Bandwidth: 112.13 GB/s
 - VRAM: 4GB GDDR5
 - DX API Version: 11
 - DX Feature Level: 11_1
 - DX Max supported: 12 (12_1)
 - Driver Version: 399.07
 - Build 1: [https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.666](https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.666)
 - Build 2:[https://github.com/xrOxygen/xray-oxygen/releases/download/1.7f.603/xray-oxygen-AVX.7z](https://github.com/xrOxygen/xray-oxygen/releases/download/1.7f.603/xray-oxygen-AVX.7z)

More info available upon request

**Comment by ForserX** [comment]
Probably the problem is due to the multithreading. Disassembled.

**Comment by jimmon89** [comment]
is there anything more you need me to do to pin down the cause

**Comment by jimmon89** [comment]
just a shot in the dark here, but if i set my cpu affinity for xrPlay.exe to a single core, would that force the entire game to run on a single thread? or am i mistaken on how that all works?

**Comment by ForserX** [comment]
All threads will work alternately. I do not advise.

**Comment by jimmon89** [comment]
with build [https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.706](https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.706) this issue is back, but not as severe
