### ISSUE TITLE
minor bug - weapon still shows while aiming through scope

### ISSUE THREAD

**Issue by jimmon89** [xrOxygen/xray-oxygen#219]
![19-09-2018 18-39-55 zaton](https://user-images.githubusercontent.com/6391541/45785879-06074700-bc3c-11e8-9925-71f92ba8b4dc.png)
![19-09-2018 18-41-05 zaton](https://user-images.githubusercontent.com/6391541/45785883-09023780-bc3c-11e8-94c3-0986401400dd.png)
the screenshots should say it all
picture 1 is a Sig-550
and picture 2 is an SVD
while aiming with  a scope the weapon continues to show through the scope at the place it would be un-scoped, but still takes into account the zoom of the scope while erroneously showing the weapon.

 - OS: windows 7 64 bit
 - Video Resolution: 1920x1080
 - Motherboard: Gigabyte GA-78LMT-S2 Rev. 2
 - Chip set: AMD - 780G
 - South Bridge: AMD - SB700
 - RAM: 2x 8Gb - DDR3
 - RAM Bandwidth: PC3-10700 - 667MHz
 - CPU: AMD FX 6100 - 3.1GHz - 6 core - supports AVX
 - Used PCI: Express 16x
 - GPU: Zotac nVidia Geforce GTX 1050 Ti OC Edition - Rev. A1
 - GPU Clock: 1392 MHz
 - Mem. Clock: 1752 MHz
 - Boost Clock: 1506 MHz
 - Cuda Cores: 768
 - Mem. Transfer rate: 7008 MHz
 - Mem. Interface: 128 bit
 - Memory Bandwidth: 112.13 GB/s
 - VRAM: 4GB GDDR5
 - DX API Version: 11
 - DX Feature Level: 11_1
 - DX Max supported: 12 (12_1)
 - Driver Version: 399.07
 - Build tested: [https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.701](https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.701)
Extra info available upon request

**Comment by ForserX** [comment]
Ops.

**Comment by jimmon89** [comment]
it happens

**Comment by jimmon89** [comment]
i would like to note that i tried the appveyor build that was just referenced in this ticket and the issue is still present
 - build tested: [https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.703](https://ci.appveyor.com/project/xrOxygen/xray-oxygen/build/1.7f.703)

**Comment by ForserX** [comment]
Check last commit. (ox_dev)

**Comment by jimmon89** [comment]
so the weapon is no longer showing while aimed through a scope...
however issue #214 has reared its ugly head once again
