### ISSUE TITLE
TBB Alloc or new WinAPI ThreadPool

### ISSUE THREAD

**Issue by ForserX** [xrOxygen/xray-oxygen#227]
The ThreadPool we have now is too slow. If anyone has any ideas what to use or a ready implementation, you can speak/share here.

Maybe:
* TBB Alloc
* WinAPI ThreadPool (again)
* STD ThreadPool

**Comment by Giperionn** [comment]
Both. Both is good.

**Comment by ForserX** [comment]
# Done
