### ISSUE TITLE
Add shader "toolbox"

### ISSUE THREAD

**Issue by MatthewKush** [xrOxygen/xray-oxygen#243]
I have a lot of tricks, functions variables, defines, and full shaders for just about anything imaginable. 

I am currently working on a folder called "shader_toolbox" inside gamedata/shaders that can be used on both R2 and R3/R4 (and R5 when that's done).

Some examples: Bending foliage, variety of GI solutions, shadows, PBR stuff, helpful functions, neat post-process effects (I have an "LSD" effect I've been wanting to use, could that be useful for anything?).

Timeline: Update once every night as often as possible until "complete".

In the meantime: if anyone has a specific shader or effect they need let me know as I likely have all shader code and often the accompanying C++ code.

**Comment by MatthewKush** [comment]
Helpful links:
https://thebookofshaders.com
https://mynameismjp.wordpress.com/
https://turanszkij.wordpress.com/
https://blog.selfshadow.com/
http://www.iquilezles.org/
https://0fps.net/

**Comment by ForserX** [comment]
Waiting for your toolbox. On my account there is a universal DLAA shader for all renders with a description. You can take from there and add here.

**Comment by MatthewKush** [comment]
@ForserX It's night not my time XD  Right now it's about 8PM/20:00.
This will likely be my usual time each day.

**Comment by MatthewKush** [comment]
and yes I will update with DLAA.

**Comment by ForserX** [comment]
:smiley:

**Comment by MatthewKush** [comment]
@ForserX I'm finding I'm very stretched for time right now, especially since I'm looking to get back to working full-time. I probably won't be able to work on this much at all anymore.

People can always message me for some quick help and I'll do my best, but I no longer have the free time that I used to have.

I'm closing this as there's no longer enough time with it (this isn't me being pissy for once, I'm in a good mood, I just have to get on with my life now).
