### ISSUE TITLE
Implement profiler in the hud

### ISSUE THREAD

**Issue by darkhpp** [xrOxygen/xray-oxygen#248]
It sometimes hard to detect low-performance function. So let's make a profiler that displays performance graph in the upper right side of the screen, might be useful for developers.

**Comment by SevastyanDark** [comment]
@ForserX can you assign me?

**Comment by ForserX** [comment]
Maybe use VS Profiler

**Comment by SevastyanDark** [comment]
VS profiler isn't comfortable as it can be used only when the application is closed and cant provide in-game statistics. I will play with it for a bit and say my opinion.

**Comment by Xottab-DUTY** [comment]
As far as I know, we already have a profiler.

**Comment by ForserX** [comment]
@SevastyanDark, окей, пили

**Comment by Xottab-DUTY** [comment]
Yes it is.
[xrGame/profiler.h](https://github.com/xrOxygen/xray-oxygen/blob/master/code/engine.vc2008/xrGame/profiler.h)
[xrGame/profiler.cpp](https://github.com/xrOxygen/xray-oxygen/blob/master/code/engine.vc2008/xrGame/profiler.cpp)
[xrGame/profiler_inline.h](https://github.com/xrOxygen/xray-oxygen/blob/master/code/engine.vc2008/xrGame/profiler_inline.h)

**Comment by darkhpp** [comment]
Done
