### ISSUE TITLE
Bug: Sun causing performance slowdowns

### ISSUE THREAD

**Issue by MatthewKush** [xrOxygen/xray-oxygen#254]
If you go outside in Call of Pripyat, on any version of the game really, and then look in the direction of the sun, your framerate should go down the closer towards the sun you're looking.

I noticed that GSC always refer to the sun as "fucking sun", so obviously they found something very frustrating about it. 
I noticed the sun cascade code is pretty long, when it seems like most graphic-engines I have starred and look at don't spend much time calculating the sun or it's shadows at all. I think GSC may have made it more complicated than it needs to be,

I've assigned myself to check on this hlsl-side, but I need someone to volunteer to take a look at this on the cpp side. 

I wouldn't call this a high priority as it's a bug I think that COP has always had.

**Comment by SevastyanDark** [comment]
@MatthewKush I will look into that as soon as I write profiler.

**Comment by MatthewKush** [comment]
@SevastyanDark Thanks (sorry for late reply). 

This issue is more serious than I first thought: I have some optimizations incoming, and with them on my 1070, I get ~500fps when staring at the ground at the starting position, around 250fps when looking in the exact opposite direction of the sun, and about 13fps when looking at the sun directly.

@ForserX I'm assuming you already know about the current performance issues ever since the Specter integration, or is it just me? The game is mostly a slide show which is why I've been having issues working on shaders. I would have said something sooner but I figured it was a known issue, but maybe not.  

I checked and it looks like the CPU code for AMD Ryzen cpu's still works, right? Other than that I'm assuming it has to do with directxmath integration not being finished?

**Comment by MatthewKush** [comment]
Disregard about my performance issues: I had forgot to reinstall my chipset driver.

**Comment by ForserX** [comment]
@MatthewKush, lol, fine, man

**Comment by SevastyanDark** [comment]
@MatthewKush Shall we close this now?
As for my PC, looking on the sun directly increases fps by 10-15 fps.

**Comment by MatthewKush** [comment]
@SevastyanDark No, this is still an issue. Not having my chipset driver was actually a blessing: by running so slow it exposed to me several major problems in Xray 1.6 (base, not the changes you guys have made):

1) The sun is the cause of many problems. Although I only lose 10-15 fps when looking at the sun as well right now, we shouldn't be losing any FPS at all looking at the sun. Something is very wrong with it.

2) Part of the stuttering is likely due to the way the "details"/grass is set up. In D3D11 we could use instancing or something along those lines, or it could be simply scrapped and replaced with something more efficient. The details renderer is too much of a headache for me though, so I'm avoiding this.

**Comment by MatthewKush** [comment]
I just fixed this, closing this issue.
