### ISSUE TITLE
xrPlay.exe crashes on start

### ISSUE THREAD

**Issue by DoctypeRosenthal** [xrOxygen/xray-oxygen#255]
the log says:

> * Vendor CPU: Intel
> * Detected CPU:  Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz
> * CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, TM2, AES, VMX, EST, XFSR
> * CPU cores/threads: 4/4 
> 
> Initializing File System...
> using fs-ltx ../fsgame.ltx
> Init FileSystem 1.829293 sec
>  
> FATAL ERROR
>  
> [error]Expression    : P != pathes.end()
> [error]Function      : CLocatorAPI::get_path
> [error]File          : c:\projects\xray-oxygen\code\engine.vc2008\xrcore\locatorapi.cpp
> [error]Line          : 1483
> [error]Description   : $dump$
>  

I just copy and pasted the whole shebang over to my Lost Alpha installation. Was that wrong? Sorry that I'm a douche without a clue ^^

**Comment by DoctypeRosenthal** [comment]
Thank you! :D
So how do I install it over CoP? Just copy and paste the stuffs into the game folder?

**Comment by Xottab-DUTY** [comment]
Yea, that's it)

**Comment by DoctypeRosenthal** [comment]
Question: what do I have to do to use the new engine with Shadow of Chernobyl?

**Comment by SevastyanDark** [comment]
@DoctypeRosenthal SoC runs on a different engine; you can`t combine oxygen and SoC.

**Comment by DoctypeRosenthal** [comment]
So ogsr runs... Interesting!

**Comment by Xottab-DUTY** [comment]
@SevastyanDark What? Call of Chernobyl is a mod for Call of Pripyat with it's own engine.

**Comment by SevastyanDark** [comment]
@Xottab-DUTY I mean the oxy engine is incompatible with the original SoC

**Comment by DoctypeRosenthal** [comment]
The only thing I hate about ogsr is the overdone SSAO on the vegetation. It looks cheap and ruins the 3d experience instead of enhancing it :(

**Comment by Xottab-DUTY** [comment]
I know, but you said that Call of Chernobyl is compatible with ShoC while it don't.

**Comment by DoctypeRosenthal** [comment]
@Sevastyan no he didn't.

**Comment by Xottab-DUTY** [comment]
He did!
> `EDIT: You can use OGSR or Call of Chernobyl, they're compatible.`

**Comment by DoctypeRosenthal** [comment]
So, oxy is only compatible with CoP and nothing else? Pls tell me with which mods/games it is compatible with.
SoC: no
Lost alpha: no
Clear sky: no
CoP: yes
OGSR: ?
Call of Chernobyl: ?

**Comment by Xottab-DUTY** [comment]
Only COP

**Comment by Xottab-DUTY** [comment]
Other projects are using their own engines.

**Comment by SevastyanDark** [comment]
@DoctypeRosenthal Mods using oxy as a platform, or other cop mods(but not guaranteed).

**Comment by SevastyanDark** [comment]
See [wiki](https://github.com/xrOxygen/xray-oxygen/wiki) for changelog
