### ISSUE TITLE
Omes0502

### ISSUE THREAD

**Issue by porames25** [xrOxygen/xray-oxygen#263]
**Describe the bug**

**To Reproduce**
Steps to reproduce the  @behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ForserX** [comment]
It's bugstack issues?

**Comment by Xottab-DUTY** [comment]
Это пустой багрепорт, сделанный с шаблона без изменений.
![chargerhm2_small](https://user-images.githubusercontent.com/2989212/49941918-aac8b600-ff05-11e8-8be6-6cc39c27ea24.png)
