### ISSUE TITLE
[Community] Free Escape From Tarkov standard addition and two keys

### ISSUE THREAD

**Issue by MatthewKush** [xrOxygen/xray-oxygen#267]
I know this isn't quite the right place for it, but on my EFT account I've been gifted a free Standard Edition of EFT and I also have two 14-day trial keys they gave me too.

Contributors to this repo get first dibs, just let me know where to send these codes and enjoy if you don't already have it.

**Comment by MatthewKush** [comment]
lol.
@Xottab-DUTY Open-xray people get second dibs XD Do you have EFT yet?

**Comment by ForserX** [comment]
I will send it to discord server

**Comment by MatthewKush** [comment]
@ForserX Thanks bro. If I don't respond right away, email me.

**Comment by SevastyanDark** [comment]
What is EFT? 😄

**Comment by MatthewKush** [comment]
I'm closing this because I found some people that wanted them.
