### ISSUE TITLE
Visual glitches ingame

### ISSUE THREAD

**Issue by InNoHurryToCode** [xrOxygen/xray-oxygen#289]
**Describe the bug**
Edge detection is going haywire.

**To Reproduce**
1. Crank up all the settings to maximum possible
2. Make sure that SMAA is the antialiassing mode and screenspace is OGSE
3. start a new game

**Expected behavior**
To not see yellow edge detection all over the screen 

**Screenshots**
![14-06-2019 23-05-01 (zaton)](https://user-images.githubusercontent.com/29128626/59538122-04cc2780-8ef9-11e9-95c9-44e88518674f.png)

**Specs**
 - OS: Windows 10
 - CPU: Intel Core I7-7700HQ
 - GPU: Nvidia GTX 1050 TI
 - RAM: 16 GB

**Additional context**
 - Deleted the bin files of 1.6.02 before installing xrOxygen
 - not using any mods
 - xrOxygen build: latest

**Comment by InNoHurryToCode** [comment]
I'm getting this also with different settings.

**Attachments**
[userdata.zip](https://github.com/xrOxygen/xray-oxygen/files/3292254/userdata.zip)

**Comment by ForserX** [comment]
Disable color grading

**Comment by InNoHurryToCode** [comment]
@ForserX thanks for the fast response! Where can I disable this?

**Comment by InNoHurryToCode** [comment]
Thanks for your fast response. It worked!
I wonder out of curiosity, why is my pc not capable of handling the color grading option?

**Comment by ForserX** [comment]
Shader bug, sorry

**Comment by InNoHurryToCode** [comment]
No problem @ForserX, bugs happen :). Will close the issue as there is a workaround!
