### ISSUE TITLE
Cannot load xrEngine.dll

### ISSUE THREAD

**Issue by CallOBock** [xrOxygen/xray-oxygen#303]
**Describe the bug**
При запуске игры - Cannot load xrEngine.dll

**To Reproduce**
1. Установить Steam версию игры.
2. Установить OxygenSetup.exe релиза X-Ray Oxygen 1.7f Preview 3 August 2019

**Screenshots**
![изображение](https://user-images.githubusercontent.com/33382201/63227746-7aeb5400-c1f2-11e9-8e3a-0f57550c0e38.png)

Версия ОС: Windows 10 x64
Лог файл:
[xray.log](https://github.com/xrOxygen/xray-oxygen/files/3513320/xray.log)

**Comment by Giperion** [comment]
Я посмотрю на след. неделе
