### ISSUE TITLE
CTDs with exceptions

### ISSUE THREAD

**Issue by S3r1ous** [xrOxygen/xray-oxygen#64]
stack trace:

0x00007FFA9B073FB8 KERNELBASE.dll, RaiseException() + 104 byte(s)

Last release without this crash is 851
I get this right after giving the artifact to Beard (quest) (from the Barge etc)
Seems to happen every time
Tested on DX9 and DX10 renderers
My system is Windows 10 (1709) and i have the latest VC2017 redistributables installed (14.12.25810)

**Comment by ForserX** [comment]
Wow! Thanks man, i fix it later. I'm a now fixes plugins, sorry.

**Comment by S3r1ous** [comment]
seems to be resolved with the latest builds (testing)
