### ISSUE TITLE
2 graphical? issues

### ISSUE THREAD

**Issue by S3r1ous** [xrOxygen/xray-oxygen#68]
I believe these are one of the oldest bugs...
basically when you step in water it shimmers right?
its kind of hard to explain, basicly it seems shimmering is too fast or out of sync, similar problem with anomalies

second 
R4 (dx11) renderer is too dark even during day, looks like its evening or night all the time during whole day/weather cycle

latest builds, no mods
win10, ryzen1600, rx480

**Comment by S3r1ous** [comment]
dx11 lighting seems fixed in the latest builds but water still moves erratically

**Comment by ForserX** [comment]
Okay.
