### ISSUE TITLE
Uninitialized member in InventoryOwner

### ISSUE THREAD

**Issue by FreeZoneMods** [xrOxygen/xray-oxygen#88]
https://github.com/xrOxygen/xray-oxygen/blob/5c4d0825d95cb43862c43b47f570e4a2d4da994b/code/engine.vc2008/xrGame/InventoryOwner.h#L117

Think it would be better to initialize the member in the constructor by calling EnableInvUpgrade to prevent any kinds of UB.

**Comment by ForserX** [comment]
Hmm... I check it later.

**Comment by ForserX** [comment]
К черту инглиш, я спешу. В общем, не советую, т.к. лишние затраты по памяти будут, ибо если бы были обращения, когда переменная была бы значения, то словил бы отладчик исключений. В общем, всё валидно. Имхо

**Comment by FreeZoneMods** [comment]
Какие нафиг затраты по памяти? У тебя в классе однобайтовый член m_bAllowInvUpgrade остается по-любому, и неважно, инициализирован ли он или нет (не надейся, что компилятор его вырежет за ненадобностью - поле экспортируется в скрипты). Только вот если он не инициализирован, в нем может находиться полная хрень в зависимости от фазы луны. Более того, при разных режимах сборки только что сконструированный объект может в теории иметь разные состояния неинициализированного члена, в итоге это может привести к багу, "исчезающему" в дебажной конфигурации сборки (передавай пламенный привет отладчику).
Вызов CInventoryOwner::EnableInvUpgrade только и делает, что явно выставляет этот байт в true, никаких расходов по памяти оно не вносит.
С другой стороны, реально это все не опасно, так как по факту вроде этот флаг в оригинале и не юзается. Может, стоит его вообще выпилить.

**Comment by ForserX** [comment]
Лол. А по памяти ты прав. Сорри, затупил. Я полностью код не смотрел, думал просто переменная. Ладно, ночью буду дома, посмотрю, используется ли вообще.
